apiVersion: apps/v1
kind: Deployment
metadata:
  name: rmu-fe-tactical
  labels:
    app: rmu-fe-tactical
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rmu-fe-tactical
  template:
    metadata:
      labels:
        app: rmu-fe-tactical
    spec:
      containers:
      - name: rmu-fe-tactical
        image: labcabrera/rmu-fe-tactical:latest
        ports:
        - containerPort: 8083
        env:
        - name: RMU_API_TACTICAL_URL
          valueFrom:
            configMapKeyRef:
              name: rmu-shared-configmap
              key: RMU_API_TACTICAL_URL
        - name: RMU_API_CORE_URL
          valueFrom:
            configMapKeyRef:
              name: rmu-shared-configmap
              key: RMU_API_CORE_URL
        - name: RMU_API_STRATEGIC_URL
          valueFrom:
            configMapKeyRef:
              name: rmu-shared-configmap
              key: RMU_API_STRATEGIC_URL
        - name: RMU_API_ATTACK_TABLES_URL
          valueFrom:
            configMapKeyRef:
              name: rmu-shared-configmap
              key: RMU_API_ATTACK_TABLES_URL
        - name: RMU_API_ITEMS_URL
          valueFrom:
            configMapKeyRef:
              name: rmu-shared-configmap
              key: RMU_API_ITEMS_URL
        - name: RMU_API_NPC_NAMES_URL
          valueFrom:
            configMapKeyRef:
              name: rmu-shared-configmap
              key: RMU_API_NPC_NAMES_URL
